export type StyleId='boxing'|'muay-thai'|'kickboxing'|'bjj'|'wrestling'|'judo'|'karate'|'taekwondo'|'mma';
export const styles=[
{id:'boxing',name:'Boxing',tags:['striking','cardio','home','low-equipment'],curve:'Fast fundamentals, deep mastery',fitness:'Elite cardio, shoulders, core',defense:88,beginner:96,why:['Strong cardio goals','Limited equipment','High confidence-building potential']},
{id:'muay-thai',name:'Muay Thai',tags:['striking','conditioning','competition'],curve:'Moderate: 8 limbs plus clinch',fitness:'Full-body power and conditioning',defense:92,beginner:82,why:['Likes striking','Wants practical self-defense','Enjoys hard conditioning']},
{id:'kickboxing',name:'Kickboxing',tags:['striking','weight-loss','home'],curve:'Beginner-friendly striking blend',fitness:'Fat loss, coordination, legs',defense:84,beginner:90,why:['Weight-loss friendly','Simple home drills','Great first striking style']},
{id:'bjj',name:'Brazilian Jiu-Jitsu',tags:['grappling','self-defense','gym'],curve:'Slow start, huge depth',fitness:'Core, hips, grip endurance',defense:94,beginner:78,why:['High self-defense interest','Prefers grappling','Builds calm under pressure']},
{id:'wrestling',name:'Wrestling',tags:['grappling','competition','muscle'],curve:'Demanding but direct',fitness:'Explosive strength and conditioning',defense:90,beginner:70,why:['Competition-ready','Wants athletic base','Powerful takedowns']},
{id:'judo',name:'Judo',tags:['grappling','self-defense','gym'],curve:'Moderate with breakfalls first',fitness:'Balance, grip, posterior chain',defense:86,beginner:76,why:['Practical throws','Confidence falling safely','Good gym pathway']},
{id:'karate',name:'Karate',tags:['striking','discipline','home'],curve:'Structured and progressive',fitness:'Mobility, balance, speed',defense:76,beginner:88,why:['Enjoys structure','Low equipment needs','Confidence through basics']},
{id:'taekwondo',name:'Taekwondo',tags:['striking','mobility','competition'],curve:'Accessible, kick flexibility grows',fitness:'Leg strength, agility, mobility',defense:72,beginner:86,why:['Likes kicks','Wants flexibility','Clear belt progression']},
{id:'mma',name:'MMA',tags:['striking','grappling','competition','gym'],curve:'High: blends multiple ranges',fitness:'Total-body athletic development',defense:96,beginner:68,why:['Wants complete fighting','Open to gyms','Long-term challenge']}
] as const;
export const questions=[['age','Age range',['13-17','18-29','30-44','45+']],['fitness','Fitness level',['New','Casual','Active','Athlete']],['weightLoss','Weight loss goal',['Low','Medium','High']],['muscle','Muscle gain goal',['Low','Medium','High']],['selfDefense','Self-defense interest',['Low','Medium','High']],['competition','Competition interest',['Low','Medium','High']],['equipment','Available equipment',['None','Jump rope','Bag/gloves','Full setup']],['gym','Gym access',['No','Maybe','Yes']],['home','Home workout preference',['Low','Medium','High']],['days','Training days per week',['2','3','4','5+']],['preference','Striking vs Grappling',['Striking','Grappling','Both']],['confidence','Confidence level',['Nervous','Curious','Ready']],['injury','Injury limitations',['None','Knees','Shoulders','Back']]] as const;
export const skillTrees={boxing:['Stance','Footwork','Jab','Cross','Hook','Defense','Combinations'],bjj:['Breakfall','Shrimp','Guard','Sweep','Armbar','Triangle'],muay:['Stance','Teep','Round Kick','Knees','Clinch','Elbows'],mma:['Stance Switching','Jab-Cross','Sprawl','Wall Getup','Ground Control','Transitions']};
export const workouts=[{day:'Monday',focus:'Boxing fundamentals + core',parts:['5 min jump rope','Stance and guard reps','Jab-cross rounds','Plank series','Breathing cooldown']},{day:'Wednesday',focus:'Conditioning + shadowboxing',parts:['Dynamic hips','Footwork ladder','3 x 3 min shadowboxing','Squats and pushups','Calf/hip mobility']},{day:'Friday',focus:'Technique drills',parts:['Joint prep','Slip-line defense','Combo builder','Farmer carry or towel grips','Stretch']},{day:'Saturday',focus:'Mobility and recovery',parts:['Zone 2 walk','Spine and hip flow','Light bag or solo drills','Core anti-rotation','Recovery notes']}];
export const achievements=['First Workout','7-Day Streak','100 Jabs Practiced','First Shadowboxing Session','Roadmap Week Complete','First Gym Visit'];
export const gear=['Training gloves','Hand wraps','Jump rope','Mouthguard','Rash guard','Shin guards'];
