'use client';
import { motion } from 'framer-motion';
import { Dumbbell, Flame, Lock, MapPin, Medal, Play, Shield, ShoppingBag, Sparkles, Star, Trophy, User, Zap } from 'lucide-react';
import { useEffect, useMemo, useState } from 'react';
import { achievements, gear, progress, questions, skillTrees, styles, workouts } from '@/lib/data';
type Answers=Record<string,string>;
const nav=['Home','Assessment','Results','Dashboard','Skill Trees','Training Plans','Gym Finder','Gear Store','Premium','Profile'];
function score(a:Answers){return styles.map((s)=>{let pts=55;if(a.preference==='Striking'&&s.tags.includes('striking'))pts+=18;if(a.preference==='Grappling'&&s.tags.includes('grappling'))pts+=18;if(a.preference==='Both'&&(s.tags.includes('striking')&&s.tags.includes('grappling')))pts+=20;if(a.home==='High'&&s.tags.includes('home'))pts+=10;if(a.gym==='Yes'&&s.tags.includes('gym'))pts+=8;if(a.selfDefense==='High')pts+=Math.round(s.defense/10);if(a.competition==='Yes'&&s.tags.includes('competition'))pts+=9;if(a.weightLoss==='High'&&(s.tags.includes('cardio')||s.tags.includes('conditioning')||s.tags.includes('weight-loss')))pts+=10;if(a.fitness==='New')pts+=Math.round(s.beginner/12);return {...s,match:Math.min(98,pts)}}).sort((a,b)=>b.match-a.match)}
function Section({id,title,children}:{id:string,title:string,children:React.ReactNode}){return <section id={id} className="mx-auto max-w-7xl px-4 py-12"><h2 className="mb-6 text-3xl font-black md:text-5xl">{title}</h2>{children}</section>}
function Card({children,className=''}:{children:React.ReactNode,className?:string}){return <div className={`card p-5 ${className}`}>{children}</div>}
export default function App(){const [answers,setAnswers]=useState<Answers>({preference:'Striking',home:'High',gym:'Maybe',selfDefense:'High',competition:'Maybe',weightLoss:'High',fitness:'New'});const [premium,setPremium]=useState(false);useEffect(()=>{const saved=localStorage.getItem('fightfit_answers');if(saved)setAnswers(JSON.parse(saved))},[]);useEffect(()=>localStorage.setItem('fightfit_answers',JSON.stringify(answers)),[answers]);const matches=useMemo(()=>score(answers),[answers]);const top=matches[0];return <main className="min-h-screen overflow-hidden bg-[radial-gradient(circle_at_top_left,rgba(182,255,59,.18),transparent_35%),radial-gradient(circle_at_80%_10%,rgba(255,61,46,.15),transparent_30%),#07080d]">
<nav className="sticky top-0 z-20 border-b border-white/10 bg-cage/85 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center gap-3 overflow-x-auto px-4 py-3"><b className="mr-3 flex items-center gap-2 whitespace-nowrap text-xl"><Shield className="text-neon"/>FightFit AI</b>{nav.map(n=><a className="whitespace-nowrap text-sm text-slate-300 hover:text-neon" href={`#${n.toLowerCase().replaceAll(' ','-')}`} key={n}>{n}</a>)}</div></nav>
<section id="home" className="mx-auto grid max-w-7xl items-center gap-8 px-4 py-16 md:grid-cols-2 md:py-24"><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}}><div className="pill mb-5 inline-flex gap-2"><Sparkles size={16}/> Duolingo-style fight fitness onboarding</div><h1 className="text-5xl font-black tracking-tight md:text-7xl">Find Your <span className="text-neon">Fighting Style.</span></h1><p className="mt-5 text-xl text-slate-300">Take a 2-minute assessment and get a personalized martial arts and fitness roadmap.</p><a className="btn btn-primary mt-8 inline-flex items-center gap-2" href="#assessment"><Play size={18}/>Start Assessment</a></motion.div><Card className="shadow-glow"><div className="grid grid-cols-2 gap-3">{matches.slice(0,4).map(s=><div key={s.id} className="rounded-2xl bg-black/30 p-4"><div className="text-3xl font-black text-neon">{s.match}%</div><div>{s.name}</div><div className="mt-2 h-2 rounded bg-white/10"><div className="h-2 rounded bg-neon" style={{width:`${s.match}%`}}/></div></div>)}</div></Card></section>
<Section id="assessment" title="2-Minute Assessment"><div className="grid gap-4 md:grid-cols-2">{questions.map(([id,label,opts])=><Card key={id}><label className="font-bold">{label}</label><div className="mt-3 flex flex-wrap gap-2">{opts.map(o=><button className={`pill ${answers[id]===o?'bg-neon text-black':''}`} onClick={()=>setAnswers({...answers,[id]:o})} key={o}>{o}</button>)}</div></Card>)}</div></Section>
<Section id="results" title="Your Style Match"><div className="grid gap-5 md:grid-cols-3">{matches.map((s,i)=><Card key={s.id} className={i===0?'border-neon/60 shadow-glow':''}><div className="flex items-center justify-between"><h3 className="text-2xl font-black">{s.name}</h3><b className="text-neon">{s.match}% Match</b></div><p className="mt-3 text-slate-300">Learning curve: {s.curve}. Fitness: {s.fitness}.</p><p className="mt-2">Self-defense {s.defense}/100 • Beginner {s.beginner}/100</p><ul className="mt-4 space-y-1 text-sm text-slate-300">{s.why.map(w=><li key={w}>• {w}</li>)}</ul></Card>)}</div></Section>
<Section id="dashboard" title="Gamified Dashboard"><div className="grid gap-5 md:grid-cols-4">{[['XP',progress.xp,Zap],['Level',progress.level,Star],['Daily streak',`${progress.streak} days`,Flame],['Weekly goal',`${progress.completedThisWeek}/${progress.weeklyGoal}`,Trophy]].map(([l,v,Icon]:any)=><Card key={l}><Icon className="text-neon"/><div className="mt-4 text-3xl font-black">{v}</div><div className="text-slate-400">{l}</div></Card>)}</div><div className="mt-6 grid gap-3 md:grid-cols-4">{achievements.map((a,i)=><div className={`rounded-2xl border p-4 ${progress.badges.includes(a)?'border-neon bg-neon/10':'border-white/10 bg-white/5'}`} key={a}><Medal className="mb-2 text-gold"/>{a}{i>4&&<Lock className="float-right text-slate-500" size={16}/>}</div>)}</div></Section>
<Section id="skill-trees" title="Skill Trees"><div className="grid gap-5 md:grid-cols-2">{Object.entries(skillTrees).map(([name,nodes])=><Card key={name}><h3 className="mb-4 text-2xl font-black">{name}</h3>{nodes.map((n,i)=><div key={n} className="flex items-center gap-3 py-2"><div className={`grid size-10 place-items-center rounded-full ${progress.unlocked.includes(n)?'bg-neon text-black':'bg-white/10'}`}>{i+1}</div><span>{n}</span>{i<nodes.length-1&&<span className="text-slate-500">↓</span>}</div>)}</Card>)}</div></Section>
<Section id="training-plans" title="Personalized Weekly Plan"><div className="grid gap-5 md:grid-cols-4">{workouts.map(w=><Card key={w.day}><h3 className="text-xl font-black text-neon">{w.day}</h3><p>{w.items.join(' + ')}</p><ol className="mt-3 space-y-2 text-sm text-slate-300">{w.blocks.map(b=><li key={b}>• {b}</li>)}</ol></Card>)}</div></Section>
<Section id="gym-finder" title="Local Gym Finder"><Card><MapPin className="text-ember"/><h3 className="mt-3 text-2xl font-black">Compare nearby gyms, prices, reviews, and intro programs.</h3><p className="text-slate-300">Mock beta marketplace: affiliate-ready listings for boxing clubs, BJJ academies, Muay Thai gyms, and MMA facilities.</p></Card></Section>
<Section id="gear-store" title="Starter Gear Recommendations"><div className="grid gap-4 md:grid-cols-3">{gear.map(g=><Card key={g}><ShoppingBag className="text-neon"/><h3 className="mt-3 font-black">{g}</h3><p className="text-sm text-slate-400">Beginner-safe pick with future affiliate link support.</p></Card>)}</div></Section>
<Section id="premium" title="AI Coach Premium"><Card><div className="flex flex-col gap-5 md:flex-row md:items-center md:justify-between"><div><div className="pill mb-3 inline-flex bg-gold text-black">Premium</div><h3 className="text-3xl font-black">Upload video for punch, squat, posture, and movement feedback.</h3><p className="text-slate-300">Unlock advanced plans, unlimited tracking, custom roadmaps, and analytics.</p></div><button onClick={()=>setPremium(true)} className="btn btn-primary">Upgrade</button></div></Card></Section>
<Section id="profile" title="Profile"><Card><User className="text-neon"/><h3 className="mt-3 text-2xl font-black">Beginner Athlete</h3><p className="text-slate-300">Current recommendation: {top.name}. Training {answers.days||'3'} days/week. Injury note: {answers.injury||'None'}.</p></Card></Section>
{premium&&<div className="fixed inset-0 z-30 grid place-items-center bg-black/70 p-4"><Card className="max-w-lg"><h3 className="text-3xl font-black">Go Premium</h3><p className="my-3 text-slate-300">Advanced plans, AI coaching, unlimited progress tracking, custom roadmaps, and analytics.</p><button className="btn btn-primary mr-2">Start trial</button><button className="btn bg-white/10" onClick={()=>setPremium(false)}>Not now</button></Card></div>}
<footer className="border-t border-white/10 p-8 text-center text-slate-400">FightFit AI MVP • Safe beginner guidance • Built for beta testing</footer></main>}
